In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/covid_toy.csv')

In [ ]:
df.head()

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,Mild,Kolkata,No
1,27,Male,100.0,Mild,Delhi,Yes
2,42,Male,101.0,Mild,Delhi,No
3,31,Female,98.0,Mild,Kolkata,No
4,65,Female,101.0,Mild,Mumbai,No


In [ ]:
df.isnull().sum()

,0
age,0
gender,0
fever,10
cough,0
city,0
has_covid,0


In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [ ]:
X_train.head(3)

,age,gender,fever,cough,city
82,24,Male,98.0,Mild,Kolkata
68,54,Female,104.0,Strong,Kolkata
30,15,Male,101.0,Mild,Delhi


#1.Without column Transfer


In [ ]:
from sklearn.impute import SimpleImputer

In [ ]:
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])
X_test_fever = si.fit_transform(X_test[['fever']])

In [ ]:
X_train_fever

array([[ 98.       ],
       [104.       ],
       [101.       ],
       [ 99.       ],
       [100.7260274],
       [101.       ],
       [ 99.       ],
       [ 98.       ],
       [101.       ],
       [101.       ],
       [ 98.       ],
       [ 98.       ],
       [102.       ],
       [ 99.       ],
       [ 98.       ],
       [101.       ],
       [101.       ],
       [100.       ],
       [101.       ],
       [100.       ],
       [100.       ],
       [104.       ],
       [ 99.       ],
       [100.7260274],
       [104.       ],
       [100.       ],
       [102.       ],
       [ 98.       ],
       [ 98.       ],
       [102.       ],
       [101.       ],
       [ 98.       ],
       [104.       ],
       [ 98.       ],
       [ 99.       ],
       [103.       ],
       [104.       ],
       [102.       ],
       [100.7260274],
       [103.       ],
       [101.       ],
       [100.7260274],
       [ 99.       ],
       [101.       ],
       [ 98.       ],
       [ 9

In [ ]:
X_train_fever.shape

(80, 1)

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])
X_test_cough = oe.fit_transform(X_test[['cough']])

In [ ]:
X_train_cough.shape

(80, 1)

In [ ]:
from sklearn.preprocessing import OneHotEncoder
ohe  = OneHotEncoder(drop='first',sparse_output=True)
X_train_gender = ohe.fit_transform(X_train[['gender','city']]).toarray()
X_test_gender = ohe.fit_transform(X_test[['gender','city']]).toarray()


In [ ]:
X_train_gender.shape

(80, 4)

In [ ]:
X_train_age = X_train.drop(columns=['gender','city','cough','fever']).values
X_test_age = X_test.drop(columns=['gender','city','cough','fever']).values

In [ ]:
X_train_age.shape

(80, 1)

In [ ]:
X_train_concat = np.concatenate((X_train_age,X_train_fever,X_train_cough,X_train_gender),axis=1)

In [ ]:
X_train_concat

array([[ 24.       ,  98.       ,   0.       ,   1.       ,   0.       ,
          1.       ,   0.       ],
       [ 54.       , 104.       ,   1.       ,   0.       ,   0.       ,
          1.       ,   0.       ],
       [ 15.       , 101.       ,   0.       ,   1.       ,   1.       ,
          0.       ,   0.       ],
       [ 22.       ,  99.       ,   0.       ,   0.       ,   0.       ,
          0.       ,   0.       ],
       [ 84.       , 100.7260274,   0.       ,   0.       ,   0.       ,
          0.       ,   0.       ],
       [  8.       , 101.       ,   0.       ,   0.       ,   0.       ,
          1.       ,   0.       ],
       [ 14.       ,  99.       ,   0.       ,   0.       ,   0.       ,
          0.       ,   1.       ],
       [ 81.       ,  98.       ,   1.       ,   0.       ,   0.       ,
          0.       ,   1.       ],
       [ 42.       , 101.       ,   0.       ,   1.       ,   1.       ,
          0.       ,   0.       ],
       [ 14.       , 101.   

In [ ]:
X_test_concat = np.concatenate((X_test_age,X_test_fever,X_test_cough,X_test_gender),axis=1)

In [ ]:
X_train_concat.shape

(80, 7)

#With Column Transfer

In [ ]:
from sklearn.compose import ColumnTransformer

In [ ]:
transformer = ColumnTransformer(transformers=[
    ('tnfe',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(drop='first',sparse_output=False),['gender','city'])
],remainder='passthrough')

In [ ]:
transformer

ColumnTransformer(remainder='passthrough',
                  transformers=[('tnfe', SimpleImputer(), ['fever']),
                                ('tnf2',
                                 OrdinalEncoder(categories=[['Mild',
                                                             'Strong']]),
                                 ['cough']),
                                ('tnf3',
                                 OneHotEncoder(drop='first',
                                               sparse_output=False),
                                 ['gender', 'city'])])

In [ ]:
X_train_transform=transformer.fit_transform(X_train)
X_test_transform=transformer.fit_transform(X_test)

In [ ]:
X_train_transform

array([[ 98.       ,   0.       ,   1.       ,   0.       ,   1.       ,
          0.       ,  24.       ],
       [104.       ,   1.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  54.       ],
       [101.       ,   0.       ,   1.       ,   1.       ,   0.       ,
          0.       ,  15.       ],
       [ 99.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  22.       ],
       [100.7260274,   0.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  84.       ],
       [101.       ,   0.       ,   0.       ,   0.       ,   1.       ,
          0.       ,   8.       ],
       [ 99.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          1.       ,  14.       ],
       [ 98.       ,   1.       ,   0.       ,   0.       ,   0.       ,
          1.       ,  81.       ],
       [101.       ,   0.       ,   1.       ,   1.       ,   0.       ,
          0.       ,  42.       ],
       [101.       ,   1.   

In [ ]:
X_train_transform.shape

(80, 7)